### PR TITLE
Constraints

### LINKED ISSUE #18: Need to quote strings in queries
We need to quote strings when used in ERDDAP expressions. 

This code:
```python
    kwargs = {
        'minTime<=': stop_time.value,
        'maxTime>=': start_time.value,
        'cdm_data_type=': cdm_data_type
    }

    variables = ['datasetID', 'minLongitude', 'minLatitude']
    url = e.get_download_url(dataset_id='allDatasets', variables=variables, response='csv', **kwargs)
```
produces this URL
https://erddap-uncabled.oceanobservatories.org/uncabled/erddap/tabledap/allDatasets.csv?datasetID,minLongitude,minLatitude&minTime%3C=2018-01-23T12:52:10Z&maxTime%3E=2018-01-16T12:52:10Z&cdm_data_type=TimeSeries

which gives the response:
```
Query error: For constraints of String variables, the right-hand-side value must be surrounded by double quotes. Bad constraint: cdm_data_type=TimeSeries
```

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #18

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
So this PR is okay handling lon,lat and time constraints because it only works on strings, right?https://github.com/pyoceans/erddapy/issues/18#issuecomment-360236196

**Comment by ocefpaf** [comment]
> So this PR is okay handling lon,lat and datetime inputs because it only works on strings, right?https://github.com/pyoceans/erddapy/issues/18#issuecomment-360236196

Yep. The magic is,

```python
{k: '"{}"'.format(v) if isinstance(v, str) else v for k, v in kwargs.items()}
```

**Comment by rsignell-usgs** [comment]
I'm happy it looks pretty similar to what I gchatted you yesterday!
```
e = {k: '\"{}\"'.format(v) if isinstance(v,str) for (k,v) in d.items}
```

**Comment by ocefpaf** [comment]
> I'm happy it looks pretty similar to what I gchatted you yesterday!

Not similar, identical :wink: 

But I was hoping to wait for the CIs and finally fix the failures here :cry:

**Comment by rsignell-usgs** [comment]
oh, sorry!

**Comment by ocefpaf** [comment]
No problem. Everything worked with my last commit. Let me know if you try this and if it fixes your issue.

**Pull request merged**
